In [50]:
import numpy as np
import xarray as xr
from scipy import stats 
import pandas as pd
#Others
import time
#Data visualization
import datetime
from dateutil.rrule import rrule, DAILY, HOURLY
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import matplotlib.colors as colors
from mpl_toolkits.axes_grid1 import make_axes_locatable
from matplotlib.ticker import MaxNLocator
import cmath

In [2]:
file_path = '/projectnb/msldrift/gdp/latest/gdp_v2.00.nc'
ds = xr.open_dataset(file_path)

In [3]:
file_path1 = '/projectnb/msldrift/gdp/latest/gdp_addon_v2.00.nc'
ds_diurnal = xr.open_dataset(file_path1)

In [4]:
ds

<xarray.Dataset>
Dimensions:                (traj: 17324, obs: 165754333)
Coordinates:
    ids                    (obs) int64 ...
    time                   (obs) datetime64[ns] ...
    lon                    (obs) float32 ...
    lat                    (obs) float32 ...
Dimensions without coordinates: traj, obs
Data variables: (12/55)
    ID                     (traj) int64 ...
    rowsize                (traj) int32 ...
    WMO                    (traj) int32 ...
    expno                  (traj) int32 ...
    deploy_date            (traj) datetime64[ns] ...
    deploy_lat             (traj) float64 ...
    ...                     ...
    err_sst1               (obs) float64 ...
    err_sst2               (obs) float64 ...
    flg_sst                (obs) int8 ...
    flg_sst1               (obs) int8 ...
    flg_sst2               (obs) int8 ...
    drogue_status          (obs) bool ...
Attributes: (12/16)
    title:             Global Drifter Program hourly drifting buoy collection
    history:           Version 2.00.  Metadata from dirall.dat and deplog.dat
    Conventions:       CF-1.6
    date_created:      2022-12-09T06:02:29.684949
    publisher_name:    GDP Drifter DAC
    publisher_email:   aoml.dftr@noaa.gov
    ...                ...
    contributor_name:  NOAA Global Drifter Program
    contributor_role:  Data Acquisition Center
    institution:       NOAA Atlantic Oceanographic and Meteorological Laboratory
    acknowledgement:   Elipot, Shane; Sykulski, Adam; Lumpkin, Rick; Centurio...
    summary:           Global Drifter Program hourly data
    doi:               10.25921/x46c-3620

In [5]:
ds_diurnal

<xarray.Dataset>
Dimensions:     (obs: 165754333)
Dimensions without coordinates: obs
Data variables:
    A1          (obs) float64 ...
    A2          (obs) float64 ...
    A3          (obs) float64 ...
    P1          (obs) float64 ...
    P2          (obs) float64 ...
    P3          (obs) float64 ...
    DSSTDT      (obs) float64 ...
    ERR_DSSTDT  (obs) float64 ...

In [6]:
ds.sst2.data

array([0.055, 0.04 , 0.027, ...,   nan,   nan,   nan])

In [7]:
P1 = ds_diurnal.P1

In [8]:
P1.data

array([0.12121, 0.38158, 0.64112, ...,     nan,     nan,     nan])

Total Analysis:

In [9]:
lon = np.linspace(-180, 180, 360*2)
lat = np.linspace(-90, 90, 180*2)

ret = stats.binned_statistic_2d(ds.lon, 
                                ds.lat,
                                ds_diurnal.A1.where(ds.flg_sst2==5),
                                statistic=np.nanmean, 
                                bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [10]:
np.savetxt('A1', ret.statistic.T)

In [11]:
ret1 = stats.binned_statistic_2d(ds.lon, 
                                ds.lat,
                                ds_diurnal.A2.where(ds.flg_sst2==5),
                                statistic=np.nanmean, 
                                bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [12]:
np.savetxt('A2', ret1.statistic.T)

In [13]:
lon = np.linspace(-180, 180, 360*2)
lat = np.linspace(-90, 90, 180*2)

ret2 = stats.binned_statistic_2d(ds.lon, 
                                ds.lat,
                                ds_diurnal.A3.where(ds.flg_sst2==5),
                                statistic=np.nanmean, 
                                bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [14]:
np.savetxt('A3', ret2.statistic.T)

In [15]:
#P1stat = pow(ds_diurnal.A1, ds_diurnal.P1*1j)
#P1stat[P1stat == np.nan+0j] = np.nan

In [16]:
"""ret3 = stats.binned_statistic_2d(ds.lon, 
                                ds.lat,
                                P1stat,
                                statistic=np.nanmean, 
                                bins=[lon, lat])"""

'ret3 = stats.binned_statistic_2d(ds.lon, \n                                ds.lat,\n                                P1stat,\n                                statistic=np.nanmean, \n                                bins=[lon, lat])'

In [17]:
#np.savetxt('P1complexnew', ret3.statistic.T)

In [18]:
"""ret4 = stats.binned_statistic_2d(ds.lon, 
                                ds.lat,
                                ds_diurnal.P2.where(ds.flg_sst2==5),
                                statistic=np.nanmean, 
                                bins=[lon, lat])"""

'ret4 = stats.binned_statistic_2d(ds.lon, \n                                ds.lat,\n                                ds_diurnal.P2.where(ds.flg_sst2==5),\n                                statistic=np.nanmean, \n                                bins=[lon, lat])'

In [19]:
#np.savetxt('P2', ret4.statistic.T)

In [20]:
"""ret5 = stats.binned_statistic_2d(ds.lon, 
                                ds.lat,
                                ds_diurnal.P3.where(ds.flg_sst2==5),
                                statistic=np.nanmean, 
                                bins=[lon, lat])"""

'ret5 = stats.binned_statistic_2d(ds.lon, \n                                ds.lat,\n                                ds_diurnal.P3.where(ds.flg_sst2==5),\n                                statistic=np.nanmean, \n                                bins=[lon, lat])'

In [21]:
#np.savetxt('P3', ret5.statistic.T)

Monthly Analysis:

In [22]:
time_bin = ds.time.astype('float')/(1e9*3600*24*365) - 17.75 + 1988 # in years
time_bin

<xarray.DataArray 'time' (obs: 165754333)>
array([2005.56187215, 2005.5619863 , 2005.56210046, ..., 2017.15216895,
       2017.15228311, 2017.15239726])
Coordinates:
    ids      (obs) int64 ...
    time     (obs) datetime64[ns] ...
    lon      (obs) float32 -47.95 -47.96 -47.96 -47.93 ... 32.84 32.84 32.84
    lat      (obs) float32 47.48 47.47 47.45 47.43 ... -25.55 -25.54 -25.54
Dimensions without coordinates: obs

In [23]:
lon = np.linspace(-180, 180, 360*2)
lat = np.linspace(-90, 90, 180*2)

In [24]:
januaryA1 = stats.binned_statistic_2d(ds.lon, 
                                    ds.lat,
                                    ds_diurnal.A1.where(time_bin % 1 <= 0.0849).where(ds.flg_sst2==5),
                                    statistic=np.nanmean, 
                                    bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [25]:
np.savetxt('januaryA1', januaryA1.statistic.T)

In [28]:
februaryA1 = stats.binned_statistic_2d(ds.lon, 
                                    ds.lat,
                                    ds_diurnal.A1.where(time_bin % 1 >= 0.0849).where(time_bin % 1 <= 0.1616).where(ds.flg_sst2==5),
                                    statistic=np.nanmean, 
                                    bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [29]:
np.savetxt('februaryA1', februaryA1.statistic.T)

In [30]:
marchA1 = stats.binned_statistic_2d(ds.lon, 
                                    ds.lat,
                                    ds_diurnal.A1.where(time_bin % 1 >= 0.1616).where(time_bin % 1 <= 0.2465).where(ds.flg_sst2==5),
                                    statistic=np.nanmean, 
                                    bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [31]:
np.savetxt('marchA1', marchA1.statistic.T)

In [32]:
aprilA1 = stats.binned_statistic_2d(ds.lon, 
                                    ds.lat,
                                    ds_diurnal.A1.where(time_bin % 1 >= 0.2465).where(time_bin % 1 <= 0.3287).where(ds.flg_sst2==5),
                                    statistic=np.nanmean, 
                                    bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [33]:
np.savetxt('aprilA1', aprilA1.statistic.T)

In [34]:
mayA1 = stats.binned_statistic_2d(ds.lon, 
                                    ds.lat,
                                    ds_diurnal.A1.where(time_bin % 1 >= 0.3287).where(time_bin % 1 <= 0.4136).where(ds.flg_sst2==5),
                                    statistic=np.nanmean, 
                                    bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [35]:
np.savetxt('mayA1', mayA1.statistic.T)

In [36]:
juneA1 = stats.binned_statistic_2d(ds.lon, 
                                    ds.lat,
                                   ds_diurnal.A1.where(time_bin % 1 >= 0.4136).where(time_bin % 1 <= 0.4958).where(ds.flg_sst2==5),
                                    statistic=np.nanmean, 
                                    bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [37]:
np.savetxt('juneA1', juneA1.statistic.T)

In [38]:
julyA1 = stats.binned_statistic_2d(ds.lon, 
                                    ds.lat,
                                   ds_diurnal.A1.where(time_bin % 1 >= 0.4958).where(time_bin % 1 <= 0.5807).where(ds.flg_sst2==5),
                                    statistic=np.nanmean, 
                                    bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [39]:
np.savetxt('julyA1', julyA1.statistic.T)

In [40]:
augustA1 = stats.binned_statistic_2d(ds.lon, 
                                    ds.lat,
                                    ds_diurnal.A1.where(time_bin % 1 >= 0.5807).where(time_bin % 1 <= 0.6656).where(ds.flg_sst2==5),
                                    statistic=np.nanmean, 
                                    bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [41]:
np.savetxt('augustA1', augustA1.statistic.T)

In [42]:
septemberA1 = stats.binned_statistic_2d(ds.lon, 
                                    ds.lat,
                                    ds_diurnal.A1.where(time_bin % 1 >= 0.6656).where(time_bin % 1 <= 0.7478).where(ds.flg_sst2==5),
                                    statistic=np.nanmean, 
                                    bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [43]:
np.savetxt('septemberA1', septemberA1.statistic.T)

In [44]:
octoberA1 = stats.binned_statistic_2d(ds.lon, 
                                    ds.lat,
                                      ds_diurnal.A1.where(time_bin % 1 >= 0.7478).where(time_bin % 1 <= 0.8327).where(ds.flg_sst2==5),
                                    statistic=np.nanmean, 
                                    bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [45]:
np.savetxt('octoberA1', octoberA1.statistic.T)

In [46]:
novemberA1 = stats.binned_statistic_2d(ds.lon, 
                                    ds.lat,
                                    ds_diurnal.A1.where(time_bin % 1 >= 0.8327).where(time_bin % 1 <= 0.9149).where(ds.flg_sst2==5),
                                    statistic=np.nanmean, 
                                    bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [47]:
np.savetxt('novemberA1', novemberA1.statistic.T)

In [48]:
decemberA1 = stats.binned_statistic_2d(ds.lon, 
                                    ds.lat,
                                    ds_diurnal.A1.where(time_bin % 1 >= 0.9149).where(time_bin % 1 <= 1).where(ds.flg_sst2==5),
                                    statistic=np.nanmean, 
                                    bins=[lon, lat])

/home/exf512/.conda/envs/cartopyk/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py:694: RuntimeWarning: Mean of empty slice
  stat = stat_func(np.array(bin_map[i]))


In [49]:
np.savetxt('decemberA1', decemberA1.statistic.T)